services:
  - type: web
    name: black-white-frontend
    env: static
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    branch: main
    repo: https://github.com/mohsinsultanriyad-crypto/black-white.git
